### ISSUE TITLE
ov2640_jpeg_sd_kaluga1_3 demo error

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_OV2640#5]
I just tried the ov2640_jpeg_sd_kaluga1_3 demo and I am getting this error 
```
Adafruit CircuitPython 7.0.0-alpha.4-97-gbba611336 on 2021-07-16; Kaluga 1 with ESP32S2
>>> import jpeg
Detected pid=26 ver=42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jpeg.py", line 146, in <module>
  File "jpeg.py", line 140, in main
  File "jpeg.py", line 122, in capture_image
AttributeError: 'module' object has no attribute 'OV2640_COLOR_JPEG'
>>> import adafruit_ov2640
>>> dir(adafruit_ov2640)
['__class__', '__name__', 'const', '__file__', '__version__', 'I2CDevice', 'digitalio', 'imagecapture', 'pwmio', 'time', 'OV2640', 'OV2640_SIZE_QVGA', 'OV2640_SIZE_UXGA', '__repo__', 'CTRLI', 'OV2640_COLOR_RGB', 'OV2640_COLOR_YUV', '_REG04_SET', '_COM3_BAND_SET', '_COM8_SET', '_COM9_AGC_SET', '_VV_AGC_TH_SET', '_CLKRC_2X_SVGA', '_CLKRC_2X_CIF', 'OV2640_SIZE_96X96', 'OV2640_SIZE_QQVGA', 'OV2640_SIZE_QCIF', 'OV2640_SIZE_HQVGA', 'OV2640_SIZE_240X240', 'OV2640_SIZE_CIF', 'OV2640_SIZE_HVGA', 'OV2640_SIZE_VGA', 'OV2640_SIZE_SVGA', 'OV2640_SIZE_XGA', 'OV2640_SIZE_HD', 'OV2640_SIZE_SXGA', '_resolution_info', '_ratio_table', '_ov2640_settings_cif', '_ov2640_settings_to_cif', '_ov2640_settings_to_svga', '_ov2640_settings_to_uxga', '_ov2640_settings_yuv422', '_ov2640_settings_rgb565', '_RegBits', '_SCCBCameraBase']
>>> 


```

**Comment by jerryneedell** [comment]
ah -- my bundle was out of date -- works fine with the updated library
